DROP TABLE IF EXISTS changes CASCADE;
DROP TABLE IF EXISTS project_label_assignments CASCADE;
DROP TABLE IF EXISTS project_labels CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
