apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "colign.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.api.env.jwtSecret | default (randAlphaNum 32) | quote }}
  {{- if .Values.api.env.claudeApiKey }}
  claude-api-key: {{ .Values.api.env.claudeApiKey | quote }}
  {{- end }}
  {{- if .Values.api.env.githubClientSecret }}
  github-client-secret: {{ .Values.api.env.githubClientSecret | quote }}
  {{- end }}
  {{- if .Values.api.env.googleClientSecret }}
  google-client-secret: {{ .Values.api.env.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.api.env.vapidPrivateKey }}
  vapid-private-key: {{ .Values.api.env.vapidPrivateKey | quote }}
  {{- end }}
